### ISSUE TITLE
Command Palette commands error with 'Cannot read properties of undefined (reading fsPath)'

### ISSUE THREAD

**Issue by pthon** [qishan233/copy-path-with-line-number#1]
The right-click pop-up (as shown in the README) work like a charm.

However, all 4 Command Palette commands of this extension result in the following error:

![image](https://github.com/user-attachments/assets/c2275cf9-aeb8-4f14-9662-518675e8f2a9)

**Comment by qishan233** [comment]
Thanks for reporting this issue. The new published version(v0.0.5) of this extension has fixed it. 

When all 4 commands are called through the Command Palette or shortcut keys, this extension will copy the active editor's path and the number of rows where the cursor is located.

If there is no active editor, this extension will show an error message.

Thanks again @pthon

**Comment by pthon** [comment]
Works like a charm now, thx for the quick fix via [8cd48b6](https://github.com/qishan233/copy-path-with-line-number/commit/8cd48b66166d359c4064a5c1e92c3e86ecfd5b94)
